#' Plot the curves generated by the hypsometric models
#'
#' Plot the curves generated by the fit of the twelve hypsometric models of the `fit_hypso` function, with the observed data and goodness-of-fit statistics.
#'
#' @param fit_hypso_list list resulting from the `fit_hypso` function.
#'
#' @return a list containing two elements. The first one, named `model` is the selected model - a `lm` object. The second, named `transform`, is a string to be used in the `predict_h` function.
#'
#' @export
plot_hypso <- function(fit_hypso_list) {

  df <- fit_hypso_list$obs_data

  y_name <- colnames(df)[1]
  x_name <- colnames(df)[2]

  xmax <- df %>% dplyr::pull(!!x_name) %>% max()
  ymin <- df %>% dplyr::pull(!!y_name) %>% min()

  labels <- tibble::tibble(xmax,
                   ymin)
  colnames(labels) <- c(x_name, y_name)

  labels <- fit_hypso_list$model_evaluation %>%
    dplyr::select(name, syx_perc, adj_r_squared) %>%
    dplyr::bind_cols(labels) %>%
    dplyr::arrange(syx_perc) %>%
    dplyr::mutate(name = factor(name, levels = unique(name),ordered = T))

  curve <- fit_hypso_list[[3]] %>%
    dplyr::mutate(name = factor(name, levels = levels(labels$name), ordered = T))

  ggplot2::ggplot(mapping = ggplot2::aes_string(x=x_name, y = y_name)) +
    ggplot2::geom_point(data = df)+
    ggplot2::geom_text(ggplot2::aes(label = paste0('Syx: ',round(syx_perc*100,2),'%\nR²adj:',round(adj_r_squared,3))),
              hjust = 1,
              vjust = 0,
              size = 3,
              data=labels)+
    ggplot2::geom_line(data = curve, color = 'steelblue')+
    ggplot2::facet_wrap(~name)

}
